
const submitters = {
    thea: {     user: "@TheaVanherst" },
    stella: {   user: "@StellaEmpyrea" },
    alex: {     user: "Alex_Miles" },
    xal: {      user: "@Crusaya" },
    jolly: {    user: "Mr Jolly" },
    rust: {     user: "Chidi" },
    atlas: {    user: "Atlas" },
    pizza: {    user: "PizzaEgger"},
    riggi: {    user: "@GalaxyTigress"},
    luna: {     user: "@MissMixTape"},
    lunar: {    user: "@RealLunar57"},
    lavlav: {   user: "LavenderFox"},
    yoLander: { user: "@valvetrova"}};

const splash = [
    [false, "Now with even more characters!"],
    [false, "As seen on TV!"],
    [false, "Moderately attractive!"],
    [false, "Now on mobile!"],
    [false, "90% bug free!"],
    [false, "A queer coded this?"],
    [false, "Queer coded? Yeah, they did."],
    [true,  "Big tits and bigger women!", submitters.stella],
    [false, "Endless Calcium!", submitters.pizza],
    [true,  "Pissweed legal!"],
    [false, "Oh god, my back!", submitters.pizza],
    [false, "More than you can handle!", submitters.atlas],
    [true,  "Give it a hugjob!", submitters.atlas],
    [true,  "So true!"],
    [true,  "Support women's right's AND women's wrongs!", submitters.stella],
    [false, "Sad!", submitters.alex],
    [false, "20% Bidness!", submitters.alex],
    [false, "She's a changeling!", submitters.alex],
    [false, "Spoilers!"],
    [false, "Bangin' bouncy cement, yo!", submitters.alex],
    [true,  "Don't look up 'Marge Simpsons Chrysalis'!"],
    [false, "Karl, play a record!", submitters.alex],
    [false, "The juice is loose!", submitters.alex],
    [false, "Let's give them an airshow!", submitters.alex],
    [true,  "Scorched arse policy.", submitters.alex],
    [false, "How about we mr ro-not?", submitters.alex],
    [false, "That's cap, your honour.", submitters.alex],
    [false, "Always Hasbin.", submitters.alex],
    [false, "But her aim's gettin' better!", submitters.alex],
    [true,  "'Fuck, i love being rimmed'", submitters.jolly],
    [false, "Thea Van hurts", submitters.alex],
    [true,  "I hope we're having Germans.", submitters.alex],
    [true,  "Executed on state tv!", submitters.rust],
    [false, "'Bang and the dirt is gone!'"],
    [true,  "'I'll see you by the canal m8'", submitters.alex],
    [true,  "I'll give you an applesmack", submitters.alex],
    [true,  "The element of subbing!", submitters.alex],
    [true,  "Changlingus", submitters.alex],
    [true,  "Are you jealous of my billion boyfriends?", submitters.alex],
    [true,  "Is this a fukin' Beastars reference?", submitters.alex],
    [false, "They don't know that I have fooled them all!", submitters.alex],
    [false, "Rei William Johnson!", submitters.alex],
    [false, "'tumblr says slow'", submitters.alex],
    [false, "That's right, Jay.", submitters.alex],
    [false, "That's right, Mike."],
    [false, "Demon-core approved!"],
    [false, "Human instrumentality!"],
    [true,  "Nightmare Poon!"],
    [false, "Wine or cheese?"],
    [false, "Vinyl Cheese!"],
    [false, "Helvetica Standard!"],
    [false, "Instead of spreading rumours about me-"],
    [false, "Ay moji!"],
    [false, "Princess Thea mora Cadenza!"],
    [false, "Dillweed!"],
    [false, "Pony Friends Forever!"],
    [false, "The apples are behind it all!"],
    [false, "Princess demandy pants!"],
    [false, "Gaslight, Gatekeep, Girlboss!"],
    [false, "...ooONE THOUSAND YEARS! DUNGEON!"],
    [false, "🅱️eter 🅱️iffin!"],
    [false, "Ms 🅱️aint!"],
    [true,  "🅱️inston 🅱️inted!"],
    [true,  "ENDLESS TRASH!"],
    [true,  "Fucking god damn... Bigger tits he says..."],
    [true,  "5th tit revision in a row..."],
    [true,  "not thicc enough he says make them biGGER"],
    [true,  "As if giving two planets of an ass wasn't enough"],
    [true,  "...bigger tits I caNT BELIE-"],
    [true,  "Ms. Taint!"],
    [true,  "A definite mercy main!"],
    [true,  "We put the large in largesse!", submitters.stella],
    [true,  "Our mommy, who art in heaven.", submitters.stella],
    [true,  "CURSE OF BAST 𓅓𓇋𓃭𓈎𓇌 𓃀𓅱𓃀𓋴", submitters.stella],
    [true,  "CURSE OF ISIS 𓆑𓅂𓂧 𓅓𓇌 𓅓𓄿𓋴", submitters.stella],
    [true,  "Bigger and better by any means necessary!"],
    [true,  "Growth accelerationism!"],
    [true,  "Fuck JQuery!"],
    [false, "Written in universal code!"],
    [false, "Hello World"],
    [true,  "100% france free!"],
    [false, "And that's how Equestria was made!"],
    [false, "It needs to be about 20% cooler."],
    [false, "Oatmeal!? Are you crazy?"],
    [false, "Let the commenting commence!"],
    [false, "vahntose-tolerant!"],
    [true,  "Imagine being shorter than 1000km..."],
    [true,  "Drcocktopus!", submitters.alex],
    [false, "Like the mcdonalds mcflurry machine", submitters.alex],
    [false, "Love is-in-bloom!"],
    [true,  "Awarded the VOREWARE seal of approval!"],
    [true,  "574 INCHES of Fat milky Borzoi JUGS", submitters.stella],
    [true,  "you've got curves she's got curves", submitters.stella],
    [true,  "'I WANT TO FUCK A DEER!!!!'", submitters.xal],
    [true,  "They call me Mommy too!", submitters.xal],
    [false, "Do you want to buy my nfcheese?"],
    [true,  "Skygracer blocked me."],
    [true,  "Say my name."],
    [false, "Queries?"],
    [true,  "Remember; No hetero."],
    [true,  "Never go full homo."],
    [false, "The lettuce won!"],
    [false, "Nationalize Greggs!", submitters.alex],
    [false, "Let's go, In and out, 20 minute adventure"],
    [false, "Chewsday!"],
    [false, "What's your damage?"],
    [false, "They won't touch radio demon"],
    [true,  "'you smoke cigars, i smoke cock'", submitters.stella],
    [true,  "IT IS FOCKING MINGING", submitters.stella],
    [true,  "🐱 🌌 🥛 🌎", submitters.stella],
    [true,  "average fuck enjoyer", submitters.stella],
    [true,  "🐶 🍈 🍈", submitters.stella],
    [true,  "Your size will now serve a greater purpose", submitters.stella],
    [true,  "2 pints of Albanians, and a packet of Quavers"],
    [false, "It's monday, or as I call it; tuesday"],
    [false, "It's tuesday, or as I call it; wednesday"],
    [false, "It's wednesday, or as I call it; thursday"],
    [false, "It's thursday, or as I call it; friday"],
    [false, "It's friday, or as I call it; saturday"],
    [false, "It's saturday, or as I call it; sunday"],
    [false, "It's sunday, or as I call it; monday"],
    [false, "Tory power stance!"],
    [false, "Hello there, my little ponies!"],
    [false, "One ticket to Barbie™, please!"],
    [false, "LEGALIZE NUCLEAR BOMBS."],
    [true,  "certified grandfather cock!", submitters.stella],
    [true,  "It's half past cock o'clock!", submitters.stella],
    [true,  "I FEEL LIKE A FUCKING CELEBRITY IN THIS TOWN!", submitters.stella],
    [true,  "Unexpected titties in baggage area", submitters.stella],
    [true,  "Unexpected cock in titty area", submitters.stella],
    [true,  "Miss Vahn permits you to jack-off in class", submitters.stella],
    [true,  "Non-stop girl cock!"],
    [false, "I am currently in your web browser."],
    [false, "Everyone wants me carnally."],
    [false, "hi, can you hear me"],
    [false, '"I AM the lgbt!" - Palpatine'],
    [true,  "Try using two brain cells!"],
    [true,  "Pingas!"],
    [true,  "Charles de galls! (Girl Balls)"],
    [true,  "The cock & balls are like twin sisters to me."],
    [true,  "Give me liberty or give me cocks and cum."],
    [true,  "Give me your Balls.", submitters.stella],
    [true,  "Give me two cocks or give me GIGANTIC BALLS.", submitters.stella],
    [true,  "Boundless Ass!", submitters.stella],
    [true,  "Boneless ass, u say?"],
    [true,  "Ass on the bone!"],
    [true,  "#RIPYandereDev"],
    [true,  "Cockmorton!"],
    [true,  "A certified cock and ball factory owner!"],
    [true,  '"Getting fucked in the ass was great!"'],
    [true,  "Sorry I missed your call, I was dual wielding."],
    [true,  'Version 1.1: - Removed sex'],
    [true,  "I'm so sane I'm so normal"],
    [true,  "-and for my next trick, no hands!"],
    [true,  "France Destroyer 9000"],
    [true,  "Horse Fucker 5000"],
    [true,  "9 inch nailed?"],
    [true,  "Hurray for showing penis!"],
    [true,  "Mom, dad, this is my fuck clown"],
    [true,  "Karl Marx at the kid's choice awards!"],
    [true,  "Pissing all by yourself, handsome?"],
    [true,  "Your boyfriend is too small."],
    [true,  "If god turns his back on you, grab his ass."],
    [false, "Thea Marie Vanqueer"],
    [false, "I do not vibe with this universe."],
    [false, "No evidence of paranormal activity found."],
    [false, "Like the joker, but for women!"],
    [false, "The vaccine makes you gay? Good."],
    [false, "Corn on the orb!"],
    [false, "LIVE SLUG REACTION"],
    [false, "One hour, no lean."],
    [false, "No beaches?"],
    [false, "An epic swag adventure!"],
    [false, "Based!"],
    [false, "Touching grass is not enough!"],
    [false, "Caught in 144p", submitters.stella],
    [false, "That wasn't very cash money of you!", submitters.stella],
    [false, "So... is there a mr. paint?"],
    [false, "Definitely a Honda Civic 2002 moment."],
    [false, "If you're cold, they're cold."],
    [false, "asexual nicki minaj moodboard"],
    [false, "Skill Issue?"],
    [false, "Remember; no micro."],
    [false, "Post neighsal drip!"],
    [false, "Literally Hasbin Hotel."],
    [false, "Forgive me if I withhold my enthusiasm!"],
    [false, "The fun has been doubled!"],
    [true,  "Asbestos cocksweat!"],
    [true,  "What's the point of this little slut!"],
    [true,  "The communist cycle of covering yourself in cum!"],
    [true,  "Monster fucking is second nature to us transgenders"],
    [true,  "‘The Dog’ from Teletubbies!"],
    [true,  "A makeshift cock!"],
    [true,  "Please fuck me relentlessly!"],
    [true,  "B😏lls"],
    [false, "Highly throwable imp!"],
    [false, "A bouncy cement factory named Tim!"],
    [false, "Krill issue!"],
    [false, "Krillex!"],
    [false, "Why would you ever sit there?"],
    [false, "Clown money to usd exchange rate is 1:1!"],
    [false, "Unregistered Hypercam!"],
    [false, "Release the bees!"],
    [false, "Kept you waiting, huh?"],
    [false, "Contains 50% alcohol!"],
    [false, "Mr electric, kill him! ⚡ "],
    [false, "I have to survive... no matter what!!"],
    [false, "I'm experiencing child like wonder!"],
    [false, "A 'Transitional Directory Controller'? What?"],
    [false, "'Accelerationism'? Is that a fast car?"],
    [false, "Your local socialist!"],
    [false, "Dad, what's is 'FNAF lore'?"],
    [false, "Shitpost Boutique!"],
    [false, "THE VAHNHATTAN PROJECT"],
    [true,  "Suck on this springcock", submitters.alex],
    [true,  "@TheaVanherst ANNAL 1800?", submitters.alex],
    [true,  "nah, analchist", submitters.alex],
    [true,  "lightnin mcqueen is the arsehole and im the cock", submitters.jolly],
    [true,  "You can't say moon without 'moo'!", submitters.lunar],
    [false, "Brain stupid!", submitters.lunar],
    [true,  "I'm fi-UCKED", submitters.stella],
    [true,  "574 INCHES OF Fat milky Borzoi JUGS", submitters.stella],
    [true,  "E621's 'Demon_Core_In_Ass' tag!"],
    [true,  "Rule 34, if it exist there is porn of it.", submitters.lunar],
    [false, "Don't trust Blender's 'edit' mode's symmetry.", submitters.lunar],
    [false, "Moon Jumpscare!"],
    [true,  "gott ist tot", submitters.stella],
    [false, "god is dead, and I'M the victor!"],
    [false, "get owned theologists", submitters.stella],
    [false, "It all returns to nothing", submitters.stella],
    [false, "we are the hope of the godless 🎵"],
    [false, "get me thirty minutes... in a room alone with god~ 🎵"],
    [false, "a glint of white to hide the knife 🎵"],
    [false, "let him know who took his throne 🎵"],
    [false, "Where's theapology?", submitters.xal],
    [false, "I hope it doesn't rain-...deer", submitters.luna],
    [false, "Dunkin' doe-...nuts!", submitters.luna],
    [false, "Hello, it's me; Jim Generic."],
    [false, "I can smell girlfailure pussy a mile away"],
    [true,  "I am the one who cocks.", submitters.xal],
    [true,  "JESSIE! WE NEED TO COCK.", submitters.xal],
    [false, "Huh? Whuh?", submitters.yoLander],
    [false, "WE AGREE!"],
    [false, "Legalise nuclear bombs"],
    [false, "Cow the Cat!"],
    [false, "What do you mean 'what do you mean'?"],
    [false, "That wasn't very big money!"],
    [true,  "Schizo coding!"],
    [false, "Gay little cat!"],
    [true,  "Fuck full fat milk!"],
    [false, "Mutually Assured Eepy", submitters.lavlav],
    [false, "Get in the bouncy cement mines!"],
    [false, "don't talk to me or my 500 glitter bombs."],
    [false, "ar ar arar ar"],
    [true,  "574 inches of fat borzoi milky jugs!", submitters.stella],
    [false, "now we're cooking with a runaway demon core.", submitters.stella],
    [false, "The Van from VanH!"]
    [false, "HAMMOND!"],
    [true,  "Cracker"],
    [false, "A Royality free website!"],
    [false, "/// POLICE ASSAULT IN PROGRESS ///"],
    [false, '"she is the pitbull of ww2 facts"', submitters.alex],
    [false, "3 figure energy drink purchases! (£1.00)"],
    [true,  '"fuck off and swivel"'],
    [false, "Blueberry Pomegranate Acai!"],
    [true,  "oc doesn't include 2 hues and 3 colours; SHIT."],
    [false, "the empyrean gamble!"],
    [false, "what the barnacles!"],
    [false, "Erm, what the sigma."],
    [false, "you're embarrassing me in front of the wizards", submitters.stella],
    [true,  "The cat called 'Shitass'!"],
    [true,  "Vanh.fart!"],
    [true,  "IS THAT THE GRIM REAPER?!", submitters.stella],
    [false, "Finally, the finals.", submitters.luna],
    [true,  'The Glitter bomb named "Garry Glitter"!'],
    [false, 'Oh, NOW she admits it.', submitters.stella],
    [false, "I didn't mean to be so adorable and funny!"],
    [true,  "Penis Prager!"],
    [true,  "Do you have books in your barn?"],
    [false, "0 Days without nonsense"],
    [false, "learn from mistakes of those who take my advice."],
    [false, "You have 5 minutes remaining."],
    [false, "Ever heard of dark humour, buddy."],
    [true,  '"Who the hell is a PDF File?"'],
    [true,  '"bailiff, whack his peepee."', submitters.stella],
    [true,  '"I thlamm my penith in the car door"'],
    [false, "citation needed!"],
    [false, "Thank GOD i'm the normal one here."],
    [true,  "Throw me to the wolves, I'll come back a father."],
    [false, "Unlucky."],
    [false, "IT ESCAPED."],
    [false, "Let it grow, sister"],
]

export { splash, submitters }