
const submitters = {
    thea: {
        user: "Thea" },
    stella: {
        user: "Stella" },
    alex: {
        user: "Alex_Miles" },
    jolly: {
        user: "Mr Jolly" },
    rust: {
        user: "Chidi" },
    atlas: {
        user: "Atlas" },
    pizza: {
        user: "PizzaEgger"},
}

const splash = [
    [false, "Now with even more characters!"],
    [false, "As seen on TV!"],
    [false, "Moderately attractive!"],
    [false, "Now on mobile!"],
    [false, "90% bug free!"],
    [false, "A queer coded this?"],
    [false, "Queer coded? Yeah, they did."],
    [true,  "Big tits and bigger women!", submitters.stella],
    [false, "Endless Calcium!","PizzaEgger"],
    [true,  "Pissweed legal!"],
    [false, "Oh god, my back!","PizzaEgger"],
    [false, "More than you can handle!", submitters.atlas],
    [true,  "Give it a hugjob!", submitters.atlas],
    [true,  "So true!"],
    [true,  "Support women's right's AND women's wrongs!", submitters.stella],
    [false, "Sad!", submitters.alex],
    [false, "20% Bidness!", submitters.alex],
    [false, "She's a changeling!", submitters.alex],
    [false, "Spoilers!"],
    [false, "That's right, Jay.", submitters.alex],
    [false, "That's right, Mike."],
    [false, "Karl, play a record!", submitters.alex],
    [true,  "Don't look up 'Marge Simpsons Chrysalis'!"],
    [false, "The juice is loose!", submitters.alex],
    [false, "Let's give them an airshow!", submitters.alex],
    [false, "Bangin' bouncy cement, yo!"],
    [true,  "Scorched arse policy.", submitters.alex],
    [false, "How about we mr ro-not?", submitters.alex],
    [false, "That's cap, your honour.", submitters.alex],
    [false, "Always Hasbin.", submitters.alex],
    [false, "But her aim's gettin' better!", submitters.alex],
    [true,  "'Fuck, i love being rimmed'", submitters.jolly],
    [false, "Thea Van hurts", submitters.alex],
    [true,  "I hope we're having Germans.", submitters.alex],
    [false, "Demon-core approved!"],
    [false, "Human instrumentality!"],
    [false, "It's wednesday, or as I call it; Thursday"],
    [true,  "Executed on state tv!", submitters.rust],
    [false, "'Bang and the dirt is gone!'"],
    [true,  "'I'll see you by the canal m8'", submitters.alex],
    [true,  "I'll give you an applesmack", submitters.alex],
    [true,  "The element of subbing!", submitters.alex],
    [true,  "Nightmare Poon!"],
    [true,  "Changlingus", submitters.alex],
    [false, "Wine or cheese?"],
    [false, "Vinyl Cheese!"],
    [false, "Helvetica Standard!"],
    [false, "Instead of spreading rumours, how about-!"],
    [true,  "Are you jealous of my billion boyfriends?", submitters.alex],
    [true,  "Ay moji!"],
    [true,  "🅱️eter 🅱️iffin!"],
    [true,  "Fucking god damn... Bigger tits he says..."],
    [true,  "ENDLESS TRASH!"],
    [true,  "5th tit revision in a row..."],
    [true,  "not thicc enough he says make them biGGER"],
    [true,  "As if giving two planets of an ass wasn't enough"],
    [true,  "...bigger tits I caNT BELIE-"],
    [true,  "'tumblr says slow'", submitters.alex],
    [true,  "🅱️inston 🅱️inted!"],
    [true,  "A definite mercy main!"],
    [true,  "We put the large in largesse!", submitters.stella],
    [true,  "Our mommy, who art in heaven.", submitters.stella],
    [true,  "Bigger and better by any means necessary!"],
    [true,  "Growth accelerationism!"],
    [true,  "CURSE OF BAST 𓅓𓇋𓃭𓈎𓇌 𓃀𓅱𓃀𓋴", submitters.stella],
    [true,  "CURSE OF ISIS 𓆑𓅂𓂧 𓅓𓇌 𓅓𓄿𓋴", submitters.stella],
    [true,  "Fuck JQuery!"],
    [false, "Written in universal code!"],
    [false, "Hello World"],
    [true,  "100% france free!"],
    [false, "And that's how Equestria was made!"],
    [false, "It needs to be about 20% cooler."],
    [false, "Oatmeal!? Are you crazy?"],
    [false, "Let the commenting commence!"],
    [false, "vahntose-tolerant!"],
    [true,  "Imagine being shorter than 1000km..."],
    [true,  "Drcocktopus!"],
    [false, "Like the mcdonalds mcflurry machine"],
    [false, "Love is-in-bloom!"],
    [true,  "574 INCHES of Fat milky Borzoi JUGS", submitters.stella],
    [true,  "youve got curves shes got curves", submitters.stella],
    [true,  "Awarded the VOREWARE seal of approval!"]
]

export { splash }